# Run check and build of the lib using the Bitcraze builder docker image
name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, lab-mac, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip build setuptools
        python3 -m pip install pre-commit

    - name: Code quality checks
      run: pre-commit run --all-files

    - name: Build wheel
      run: python3 -m build --wheel

    - name: Install wheel
      run: pip install ./dist/*.whl

    - name: Test
      run: python3 -m unittest discover test/

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install pdoc3 pyyaml
      - name: Build docs
        run: ./tools/build-docs/build-docs
